# title: "Data Science Capstone"
# author: "Víctor Yeste"
# date: "10/20/2021"

library(shiny)
library(tm)
library(dplyr)

# Load n-gram frequencies generated by get-ngram-freq.R file

ngrams.1 <- readRDS("data/ngrams.1.05.RData")
ngrams.2 <- readRDS("data/ngrams.2.05.RData")
ngrams.3 <- readRDS("data/ngrams.3.05.RData")
ngrams.4 <- readRDS("data/ngrams.4.05.RData")

# Prepare data

prepareData <- function(data) {
    
    # Clean data
    
    data <- tolower(data)
    data <- gsub("\\S+[@]\\S+", "", data, ignore.case = FALSE, perl = TRUE)
    data <- gsub("@[^\\s]+", "", data, ignore.case = FALSE, perl = TRUE)
    data <- gsub("#[^\\s]+", "", data, ignore.case = FALSE, perl = TRUE)
    data <- gsub("^\\s+|\\s+$", "", data)
    data <- stripWhitespace(data)
    
    # Remove bad words
    
    con <- file("data/bad-words.txt", open = "r")
    badWords <- readLines(con, encoding = "UTF-8", skipNul = TRUE)
    badWords <- iconv(badWords, "latin1", "ASCII", sub = "")
    close(con)
    data <- removeWords(data, badWords)
    
    # Transform to character vector of words
    
    data <- unlist(strsplit(data, " "))
    
    return(data)
    
}

# Get prediction, necessary in another function to be recursive

getPrediction <- function(data, ngrams) {
    
    data.length <- length(data)
    
    if(ngrams == 2){
        data.used <- data[data.length]
        result <- ngrams.2 %>% filter(token == data.used)
        return(result$outcome[1:3])
    } else if(data.length == 2){
        data.used <- paste(data[data.length-1], data[data.length])
        result <- ngrams.3 %>% filter(token == data.used)
        if(nrow(result) >= 1){
            return(result$outcome[1:3])
        } else {
            return(getPrediction(data, ngrams - 1))
        }
    } else if(data.length > 2){
        data.used <- paste(data[data.length-2], data[data.length-1],
                           data[data.length])
        result <- ngrams.4 %>% filter(token == data.used)
        if(nrow(result) >= 1){
            return(result$outcome[1:3])
        } else {
            return(getPrediction(data, ngrams - 1))
        }
    }
    
    return(NA)
    
}

# Predict next word of the word or phrase the user introduced

predictWord <- function(data, nWord = 0) {
    
       data <- prepareData(data)
       
       data.length <- length(data)
       
       if(data.length == 0) {
           pred <- ngrams.1$token[1:3]
       } else if(data.length == 1){
           pred <- getPrediction(data, ngrams = 2)
       } else if(data.length == 2){
           pred <- getPrediction(data, ngrams = 3)
       } else if(data.length > 2){
           pred <- getPrediction(data, ngrams = 4)
       }
       
       if(nWord == 0) {
           return(pred)
       } else if(nWord <= 3) {
           return(pred[nWord])
       }
       
}

# Define server logic required to show the predictions

shinyServer(function(input, output) {
    
    output$userTextResult <- renderText(input$userText)
    
    observe({
        nPred <- input$nPred
        output$pred1 <- reactive(predictWord(input$userText, 1))
        if(nPred >= 2) {
            output$pred2 <- reactive(predictWord(input$userText, 2))
            if(nPred == 3) {
                output$pred3 <- reactive(predictWord(input$userText, 3))
            } else {
                output$pred3 <- NULL
            }
        } else {
            output$pred2 <- NULL
            output$pred3 <- NULL
        }
    })

})